### ISSUE TITLE
Unclear warning "Probably you need a username, password and realm"

### ISSUE THREAD

**Issue by netsensei** [LibreCat/Catmandu-OAI#23]
Commit f0d48b83d74867fe656a080aefbc56bbf033357a introduces a new warning:

````
Probably you need a username,password and realm at /Users/matthiasvandermaesen/.plenv/versions/5.22.0/lib/perl5/site_perl/5.22.0/Catmandu/Importer/OAI.pm line 368.
````

Caused by this line:

````
        carp "Probably you need a username,password and realm" unless $self->realm;
````

In our case, "realm" is not used / optional. We log in with NTLM through a username & password. When we pass an empty string or undef, we still get this message.

Also, the message is not really clear in it's wording ('probably', non-exclusive 'and') .

**Comment by phochste** [comment]
Ah the problem is that with Basic Authorisation the realm is required.

**Comment by phochste** [comment]
0.17 is on its way to cpan
