### ISSUE TITLE
XSLT handler to process metadata DOM 

### ISSUE THREAD

**Issue by nichtich** [LibreCat/Catmandu-OAI#5]
XML formats can best be processed with XSLT but this importer provides no hook to perform XSLT processing in the DOM before it is serialized to a string (`_metadata`) or to XML Struct. An XSLT handler should only load XSLT script once, allow piping multiple XSLT scripts and finally serialize/convert like raw or struct handler.

P.S: The handler might better be part of Catmandu::XML to not add another xs-module dependency (XML::LibXSLT)

**Comment by phochste** [comment]
Why is this? We want to construct a Perl HASH structure to do further processing on OAI-PMH data. Can you give an example for the XSLT processing case?

**Comment by nichtich** [comment]
XSLT scripts and knowledge already exists (for instance [MARC to MODS](http://www.loc.gov/standards/mods/mods-conversions.html)) so it can be easier to add an XSLT processing step *before* further processing as Perl HASH. I'll create a patch to illustrate the point!

**Comment by nicolasfranck** [comment]
can this be closed?
