### ISSUE TITLE
Support GetRecord

### ISSUE THREAD

**Issue by nichtich** [LibreCat/Catmandu-OAI#9]
To get a single record with option `identifier`

**Comment by nicolasfranck** [comment]
Sounds reasonable as it has the same format as ListRecords.

But..when a record is not found, the API returns an error code:
```
http://memory.loc.gov/cgi-bin/oai2_0?verb=GetRecord&metadataPrefix=oai_dc&identifier=sfsf
```
```
<OAI-PMH xmlns="http://www.openarchives.org/OAI/2.0/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd">
  <responseDate>2017-01-04T10:59:49Z</responseDate>
  <request verb="GetRecord" identifier="sfsf" metadataPrefix="oai_dc">http://memory.loc.gov/cgi-bin/oai2_0</request>
  <error code="idDoesNotExist">
The value of identifier (sfsf) is unknown or illegal in this repository
  </error>
</OAI-PMH>
```

How should we handle this? There are two options:

* let it fail. It's how the API works
* or: return an empty array

**Comment by phochste** [comment]
The package should be consistent in behavior. Use the standard procedure how any OAI error response is handled.

Of course there will be a next question: better handling of OAI error messages.

**Comment by phochste** [comment]
Fixed in the dev branch.
